# Generated by Django 3.1.6 on 2021-03-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Courses', models.CharField(max_length=15)),
                ('Fall2018', models.CharField(max_length=15)),
                ('Spring2019', models.CharField(max_length=15)),
                ('Fall2019', models.CharField(max_length=15)),
                ('Spring2020', models.CharField(max_length=15)),
                ('Fall2020', models.CharField(max_length=15)),
                ('Spring2021', models.CharField(max_length=15)),
                ('Fall2021', models.CharField(max_length=15)),
                ('Spring2022', models.CharField(max_length=15)),
            ],
        ),
    ]
